site:
  name: Heartland Transpersonal Alliance
  site: 'https://heartlandtranspersonalalliance.github.io'
  base: '/hta-modern'
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: Heartland Transpersonal Alliance
    template: '%s | Heartland Transpersonal Alliance'
  description: 'A nonprofit building community, education, harm reduction, and integration pathways around the safe, responsible exploration of consciousness.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Heartland Transpersonal Alliance
    images:
      - url: '~/assets/images/hta_darklogo.png'
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/news/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'news'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'news/category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'news/tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 3

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark'
